### ISSUE TITLE
log error

### ISSUE THREAD

**Issue by ByKyTa** [ismail0234/Benson-Map-Configs#1]
L 01/15/2019 - 21:36:49: [SM] Blaming: test\mapconfigs.smx
L 01/15/2019 - 21:36:49: [SM] Call stack trace:
L 01/15/2019 - 21:36:49: [SM]   [0] SetConVarString
L 01/15/2019 - 21:36:49: [SM]   [1] Line 162, mapconfigs.sp::SetCvarString
L 01/15/2019 - 21:36:49: [SM]   [2] Line 153, mapconfigs.sp::executeAllCommand
L 01/15/2019 - 21:36:49: [SM]   [3] Line 58, mapconfigs.sp::ExecuteMapSpecificConfigs
L 01/15/2019 - 21:36:49: [SM]   [4] Line 30, mapconfigs.sp::OnAutoConfigsBuffered

**Comment by ismail0234** [comment]
Still have problems? @ByKyTa
