### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rcon420** [ismail0234/Benson-Map-Configs#2]
L 01/07/2020 - 188:51: [SM] Blaming: mapconfigs.smx
L 01/07/2020 - 188:51: [SM] Call stack trace:
L 01/07/2020 - 188:51: [SM] [0] SetConVarString
L 01/07/2020 - 188:51: [SM] [1] Line 162, mapconfigs.sp::SetCvarString
L 01/07/2020 - 188:51: [SM] [2] Line 153, mapconfigs.sp::executeAllCommand
L 01/07/2020 - 188:51: [SM] [3] Line 58, mapconfigs.sp::ExecuteMapSpecificConfigs
L 01/07/2020 - 188:51: [SM] [4] Line 30, mapconfigs.sp::OnAutoConfigsBuffered

What is this error?

Tho I think it would be better if you would list only plugins that you don't want to use cuz my server has like +80 plugins and I got aim_, awp_, cs_, de_, etc maps kinda mess to go through everything and u can forget to add something.

Overall I like this plugin suite for my needs perfect.

**Comment by ismail0234** [comment]
@oligarhs420 
can you send config files?

**Comment by rcon420** [comment]
> @oligarhs420
> can you send config files?

[removed link] here you go.

**Comment by ismail0234** [comment]
fixed.
